components:
  schemas:
    Config.Generate.Request:
      description: |-
        A configuration that describes a set of new resources to be generated.
      type: object
      required:
        - choice
      properties:
        choice:
          type: string
          x-enum:
            ai_workload:
              x-field-uid: 1
          x-field-uid: 1
        ai_workload:
          description: |-
            A description of the infrastructure that the AI workload will run on.
          $ref: '../ai_workload/generate.yaml#/components/schemas/AiWorkload.Config.Generate.Request'
          x-field-uid: 2

